services:
    msteffens.dev:
        container_name: msteffens.dev
        build: .
        ports:
            - 14632:14632
        environment:
            - PORT=14632
            # For other sveltekit server config env vars, see https://kit.svelte.dev/docs/adapter-node#environment-variables
